- hosts: localhost
  become: true
  tasks:

    - name: Copy tailscale repository
      ansible.builtin.copy:
        src: files/fedora/etc/yum.repos.d/tailscale.repo
        dest: /etc/yum.repos.d/tailscale.repo
        owner: root
        group: root
        mode: '0644'

    - name: Remove overlay package
      community.general.rpm_ostree_pkg:
        state: absent
        name:
          - firefox
          - firefox-langpacks

    - name: Install overlay package
      community.general.rpm_ostree_pkg:
        state: present
        name:
          - ansible
          - ansible-collection-community-general
          - gnome-themes-extra
          - langpacks-hu
          - tailscale
          - unrar 

    - name: Add FlatHub repo
      ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Install packages from Flathub
      community.general.flatpak:
        state: present
        remote: flathub
        name:
          - com.bitwarden.desktop
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
          - com.spotify.Client
          - io.bassi.Amberol
          - io.github.celluloid_player.Celluloid
          - io.github.giantpinkrobots.flatsweep
          - io.missioncenter.MissionCenter
          - org.freedesktop.Platform.ffmpeg-full
          - org.freedesktop.Platform.openh264
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Contacts
          - org.gnome.DejaDup
          - org.gnome.Evince
          - org.gnome.Loupe
          - org.gnome.SimpleScan
          - org.gnome.TextEditor
          - org.gnome.Weather
          - org.gnome.baobab
          - org.gnome.clocks
          - org.gtk.Gtk3theme.Adwaita-dark
          - org.libreoffice.LibreOffice
          - org.mozilla.firefox
