- name: Copy tailscale repository
  become: true
  ansible.builtin.copy:
    src: files/tailscale.repo
    dest: /etc/yum.repos.d/tailscale.repo
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == "Fedora"

- name: Remove applications from the base OS
  community.general.rpm_ostree_pkg:
    name: "{{ base_package_remove }}"
    state: absent

- name: Install desired applications as layered packages
  community.general.rpm_ostree_pkg:
    name: "{{ layered_package_install }}"
    state: present
