- name: Copy tailscale repository
  become: true
  ansible.builtin.copy:
    src: files/tailscale.repo
    dest: /etc/yum.repos.d/tailscale.repo
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution == "Fedora"

- name: Remove applications from the base OS
  community.general.rpm_ostree_pkg:
    name: "{{ item }}"
    state: absent
    # apply_live: true  # This feature is not yet available
  loop: "{{ base_package_remove }}"

- name: Install desired applications as layered packages
  community.general.rpm_ostree_pkg:
    name: "{{ item }}"
    state: present
    # apply_live: true  # This feature is not yet available
  loop: "{{ layered_package_install }}"
